// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7wImZUjrV7XQZPPBrk3gYuStOzt7cZg8',
    appId: '1:6874426227:web:363fcc07e72d8b30bfb306',
    messagingSenderId: '6874426227',
    projectId: 'afrodance-corner',
    authDomain: 'afrodance-corner.firebaseapp.com',
    storageBucket: 'afrodance-corner.firebasestorage.app',
    measurementId: 'G-WQ2GZ347X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUB976yhSZvAdGfahRsJ3EbtUrID6lALI',
    appId: '1:6874426227:android:9d37d8e85b32b9ccbfb306',
    messagingSenderId: '6874426227',
    projectId: 'afrodance-corner',
    storageBucket: 'afrodance-corner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIan1ptbr7mLAZwtur_tsWywrsJIw5eI',
    appId: '1:6874426227:ios:48437664e1c1db5bbfb306',
    messagingSenderId: '6874426227',
    projectId: 'afrodance-corner',
    storageBucket: 'afrodance-corner.firebasestorage.app',
    iosBundleId: 'com.example.afrodanceCorner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdIan1ptbr7mLAZwtur_tsWywrsJIw5eI',
    appId: '1:6874426227:ios:48437664e1c1db5bbfb306',
    messagingSenderId: '6874426227',
    projectId: 'afrodance-corner',
    storageBucket: 'afrodance-corner.firebasestorage.app',
    iosBundleId: 'com.example.afrodanceCorner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7wImZUjrV7XQZPPBrk3gYuStOzt7cZg8',
    appId: '1:6874426227:web:0ce423ef88cfeff0bfb306',
    messagingSenderId: '6874426227',
    projectId: 'afrodance-corner',
    authDomain: 'afrodance-corner.firebaseapp.com',
    storageBucket: 'afrodance-corner.firebasestorage.app',
    measurementId: 'G-1K85SDNB9X',
  );
}
